name: wildcamp
description: Beta project. Not yet ready

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.3.1+7

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: any
  cupertino_icons: any
  file_picker: any
  firebase_auth: any
  firebase_storage: any
  flutter_rating_bar: any
  font_awesome_flutter: any
  google_fonts: any
  google_maps_flutter: any
  google_maps_flutter_web: any
  google_nav_bar: any
  google_sign_in: any
  googleapis: any
  location: any
  mailer: any
  provider: any
  rxdart: any
  transparent_image: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.2
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  image_path: "assets/logos/play_store_512.png" # "assets/logos/play_store_512.png"
  adaptive_icon_background: "#4CAF50"
  adaptive_icon_foreground: "assets/logos/res/mipmap-hdpi/ic_launcher_adaptive_fore.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/logos/play_store_512.png
    - assets/logos/res/mipmap-hdpi/ic_launcher_adaptive_fore.png
    - assets/white.jpg

